all:
  children:
    agg:
      hosts:
        c9500-stack1: { ansible_host: 10.10.0.11 }
        c9500-stack2: { ansible_host: 10.10.0.12 }
    access:
      hosts:
        c9200-acc-01: { ansible_host: 10.10.1.1 }
        c9200-acc-02: { ansible_host: 10.10.1.2 }
        c9200-acc-03: { ansible_host: 10.10.1.2 }
        c9200-acc-04: { ansible_host: 10.10.1.2 }
        c9200-acc-05: { ansible_host: 10.10.1.2 }
    firewall:
      hosts:
        asa-edge: { ansible_host: 10.10.254.1 }
    wlc:
      hosts:
        wlc9800: { ansible_host: 10.10.253.10 }
