all:
  children:
    agg:
      hosts:
        c9500-stack1: { ansible_host: 10.114.0.2 }
        c9500-stack2: { ansible_host: 10.114.0.3 }
    access:
      hosts:
        c9200-acc-01: { ansible_host: 10.114.0.4 }
        c9200-acc-02: { ansible_host: 10.114.0.5 }
        c9200-acc-03: { ansible_host: 10.114.0.6 }
        c9200-acc-04: { ansible_host: 10.114.0.7 }
        c9200-acc-05: { ansible_host: 10.114.0.8 }
        c9200-acc-06: { ansible_host: 10.114.0.9 }
        c9200-acc-07: { ansible_host: 10.114.0.X}
    firewall:
      hosts:
        asa-edge: { ansible_host: 10.10.254.1 }
    wlc:
      hosts:
        wlc9800: { ansible_host: 10.114.0.254 }
